export const GET_ALL_CUSTOMERS_REQUEST = 'GET_ALL_CUSTOMERS_REQUEST';
export const GET_ALL_CUSTOMERS_SUCCESS = 'GET_ALL_CUSTOMERS_SUCCESS';
export const GET_ALL_CUSTOMERS_FAILURE = 'GET_ALL_CUSTOMERS_FAILURE';

export const DELETE_CUSTOMERS_REQUEST = 'DELETE_CUSTOMERS_REQUEST ';
export const DELETE_CUSTOMERS_SUCCESS = 'DELETE_CUSTOMERS_SUCCESS';
export const DELETE_CUSTOMERS_FAILURE = 'DELETE_CUSTOMERS_FAILURE';

export const UPDATE_CUSTOMERS_REQUEST = 'UPDATE_CUSTOMERS_REQUEST';
export const UPDATE_CUSTOMERS_SUCCESS = 'UPDATE_CUSTOMERS_SUCCESS';
export const UPDATE_CUSTOMERS_FAILURE = 'UPDATE_CUSTOMERS_FAILURE';